INSERT INTO "Problem1" VALUES('a','false','De capaciteit C definieert niet per se het voertuig V.');
INSERT INTO "Problem1" VALUES('b','true','Het voertuig V dat genomen wordt bepaald de capaciteit C.');
INSERT INTO "Problem1" VALUES('c','true','Op de factuur F staat een uniek pakje P.');
INSERT INTO "Problem1" VALUES('d','false','Met een pakketje kan mogelijk wel het afleveradres A worden achterhaald, maar niet per se de factuur F.');
INSERT INTO "Problem1" VALUES('e','false','Uit het pakketje P is niet het geldbedrag G of de ontvanger O te achterhalen.');
INSERT INTO "Problem1" VALUES('f','false','Omdat een bezorger B meerdere voertuigen V kan hebben kun je niet een specifieke V vinden op basis van B.');
INSERT INTO "Problem1" VALUES('g','false','Omdat een voertuig V meerdere bezorgers B kan hebben die gerechtigd zijn in dat voertuig te rijden, kun je geen specifieke bezorger vinden op basis van het voertuig.');
INSERT INTO "Problem1" VALUES('h','true','De bestuurder is, op het voertuig V na nergens van afhankelijk binnen de database.');
INSERT INTO "Problem1" VALUES('i','true','De capaciteit is, op het voertuig v na, nergens van afhankelijk binnen de database');
INSERT INTO "Problem1" VALUES('j','true','Omdat de bestuurder B en de capaciteit C beiden alleen afhankelijk zijn van het voertuig V en niet van andere waarden binnen de tabel');
